[package]
name = "rs-top"
version = "0.1.0"
edition = "2024"
authors = ["Rui Jiang me@ruijiang.me"]
license = "MIT"
description = "Real-time TUI system monitor for remote hosts"
readme = "README.md"
repository = "https://github.com/ruiiiijiiiiang/rs-top"
keywords = ["tui", "monitoring", "ssh", "system", "remote"]
categories = ["command-line-utilities", "visualization", "network-programming"]

[dependencies]
color-eyre = "0.6"
ratatui = { version = "0.30", features = ["all-widgets"] }
openssh = "0.11"
tokio = { version = "1.52", features = ["full"] }
dirs = "6.0"
serde = { version = "1.0", features = ["derive"] }
toml = "1.1"
